name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: store
      uses: actions/upload-artifact@v3
      with:
        name: hbl.nsp
        path: out/hbl.nsp
