name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64

    steps:
      - name: env
        run: |
          cat /proc/cpuinfo
          free -m
      - name: checkout - project
        uses: actions/checkout@v1
        with:
          submodules: recursive
          fetch-depth: 1
      - name: deps - libnx
        run: |
          git clone https://github.com/switchbrew/libnx.git /tmp/libnx
          make -C /tmp/libnx install -j4
      - name: deps - ams libs
        run: |
          make -C lib/ams/libstratosphere -j4
          
      - uses: actions/checkout@v3
      - name: make
        run: make
      - name: store
        uses: actions/upload-artifact@v3
        with:
          name: hbl.nsp
          path: hbl.nsp
